"""Create notes table

Revision ID: 5b96f748b701
Revises: 
Create Date: 2025-07-30 12:15:28.023710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b96f748b701'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_id'), 'notes', ['id'], unique=False)
    op.create_table('note_links',
    sa.Column('from_note_id', sa.Integer(), nullable=False),
    sa.Column('to_note_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['from_note_id'], ['notes.id'], ),
    sa.ForeignKeyConstraint(['to_note_id'], ['notes.id'], ),
    sa.PrimaryKeyConstraint('from_note_id', 'to_note_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note_links')
    op.drop_index(op.f('ix_notes_id'), table_name='notes')
    op.drop_table('notes')
    # ### end Alembic commands ###
